// 파일 위치: components/aivoca/components/WordList.tsx

import React, { useState, useEffect, useRef } from 'react';
import { Word } from '../types'; // 주소를 우리 프로젝트에 맞게 수정!
import { generatePronunciation, generateExample } from '../services/geminiService'; // 주소를 우리 프로젝트에 맞게 수정!
import { Search, Edit3, Save, Volume2, BookOpen, AlertCircle, Star, CheckSquare, Square, Play, Loader2, RotateCcw, Sparkles, MoveHorizontal, Grid3X3, List } from 'lucide-react';

// ... (이 아래는 네가 준 코드와 99% 똑같아. 주소만 고쳤어!)
interface WordListProps { words: Word[]; filterType: 'ALL' | 'REVIEW'; onUpdateWord: (id: string, updates: Partial<Word>) => void; onToggleFavorite: (id: string) => void; onStartQuizWithWords: (words: Word[]) => void; onStartFavoriteQuiz?: () => void; }

const WordList: React.FC<WordListProps> = ({ words, filterType, onUpdateWord, onToggleFavorite, onStartQuizWithWords, onStartFavoriteQuiz }) => {
  const [searchTerm, setSearchTerm] = useState('');
  const [editingId, setEditingId] = useState<string | null>(null);
  const [noteInput, setNoteInput] = useState('');
  const [playingId, setPlayingId] = useState<string | null>(null);
  const [generatingExampleId, setGeneratingExampleId] = useState<string | null>(null);
  const [isRangeMode, setIsRangeMode] = useState(false);
  const [rangeStartId, setRangeStartId] = useState<string | null>(null);
  const [viewColumns, setViewColumns] = useState<1 | 2 | 3>(1);
  const audioCtxRef = useRef<AudioContext | null>(null);
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());

  useEffect(() => { if (!audioCtxRef.current) { audioCtxRef.current = new (window.AudioContext || (window as any).webkitAudioContext)({sampleRate: 24000}); } return () => { audioCtxRef.current?.close(); audioCtxRef.current = null; } }, []);
  useEffect(() => { setSelectedIds(new Set()); setIsRangeMode(false); setRangeStartId(null); }, [filterType]);

  const filteredWords = words.filter(word => { const matchesSearch = word.term.toLowerCase().includes(searchTerm.toLowerCase()) || word.definition.includes(searchTerm); if (filterType === 'REVIEW') { return matchesSearch && word.incorrectCount > 0; } return matchesSearch; });
  const incorrectWords = words.filter(w => w.incorrectCount > 0);
  const startEditing = (word: Word) => { setEditingId(word.id); setNoteInput(word.userNote || ''); };
  const saveNote = (id: string) => { onUpdateWord(id, { userNote: noteInput }); setEditingId(null); };
  const speak = async (wordId: string, text: string) => { if (playingId) return; setPlayingId(wordId); try { if (!audioCtxRef.current) { audioCtxRef.current = new (window.AudioContext || (window as any).webkitAudioContext)({sampleRate: 24000}); } const ctx = audioCtxRef.current; if (ctx.state === 'suspended') await ctx.resume(); const pcmData = await generatePronunciation(text); if (pcmData) { const numChannels = 1; const dataInt16 = new Int16Array(pcmData.buffer); const frameCount = dataInt16.length; const audioBuffer = ctx.createBuffer(numChannels, frameCount, 24000); const channelData = audioBuffer.getChannelData(0); for (let i = 0; i < frameCount; i++) { channelData[i] = dataInt16[i] / 32768.0; } const source = ctx.createBufferSource(); source.buffer = audioBuffer; source.connect(ctx.destination); source.onended = () => setPlayingId(null); source.start(); } else { setPlayingId(null); } } catch (error) { console.error("Audio playback error", error); setPlayingId(null); } }
  const handleGenerateExample = async (word: Word) => { setGeneratingExampleId(word.id); try { const result = await generateExample(word.term, word.definition); onUpdateWord(word.id, { exampleSentence: result.sentence, exampleTranslation: result.translation }); } finally { setGeneratingExampleId(null); } };
  const toggleSelection = (id: string) => { const newSet = new Set(selectedIds); if (newSet.has(id)) { newSet.delete(id); } else { newSet.add(id); } setSelectedIds(newSet); };
  const toggleSelectAll = () => { if (selectedIds.size === filteredWords.length) { setSelectedIds(new Set()); } else { setSelectedIds(new Set(filteredWords.map(w => w.id))); } };
  const handleCardClick = (id: string) => { if (editingId || playingId) return; if (!isRangeMode) { toggleSelection(id); return; } if (rangeStartId === null) { setRangeStartId(id); const newSet = new Set(selectedIds); newSet.add(id); setSelectedIds(newSet); } else { const startIdx = filteredWords.findIndex(w => w.id === rangeStartId); const endIdx = filteredWords.findIndex(w => w.id === id); if (startIdx !== -1 && endIdx !== -1) { const min = Math.min(startIdx, endIdx); const max = Math.max(startIdx, endIdx); const newSet = new Set(selectedIds); for (let i = min; i <= max; i++) { newSet.add(filteredWords[i].id); } setSelectedIds(newSet); } setRangeStartId(null); setIsRangeMode(false); } };
  const cancelRangeMode = () => { setIsRangeMode(false); setRangeStartId(null); };
  const handleStartSelectedQuiz = () => { const selectedWords = words.filter(w => selectedIds.has(w.id)); onStartQuizWithWords(selectedWords); };
  const handleStartFavoriteQuiz = () => { if (onStartFavoriteQuiz) { onStartFavoriteQuiz(); } else { const favWords = words.filter(w => w.isFavorite); onStartQuizWithWords(favWords); } }
  const handleStartIncorrectQuiz = () => { if (incorrectWords.length > 0) { onStartQuizWithWords(incorrectWords); } }

  return (
    <div className="space-y-6 animate-fade-in pb-20">
      <div className="flex flex-col gap-4">
        <div className="flex flex-col md:flex-row justify-between items-center gap-4"><h2 className="text-2xl font-bold text-white flex items-center gap-2">{filterType === 'REVIEW' ? <AlertCircle className="text-orange-500"/> : <BookOpen className="text-purple-500"/>}{filterType === 'REVIEW' ? '오답 노트 (Review)' : '나만의 단어장'}</h2><div className="relative w-full md:w-64"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500 w-4 h-4" /><input type="text" placeholder="단어 검색..." value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} className="w-full bg-slate-800 border border-slate-700 rounded-full py-2 pl-10 pr-4 text-sm text-white focus:border-purple-500 outline-none"/></div></div>
        <div className="flex flex-wrap gap-3 items-center justify-between bg-slate-800/50 p-3 rounded-xl border border-slate-700/50"><div className="flex items-center gap-2"><button onClick={toggleSelectAll} className="flex items-center gap-2 px-3 py-1.5 bg-slate-700 hover:bg-slate-600 rounded-lg text-sm text-slate-300 transition-colors">{selectedIds.size > 0 && selectedIds.size === filteredWords.length ? <CheckSquare className="w-4 h-4 text-purple-400"/> : <Square className="w-4 h-4"/>}전체</button><button onClick={() => { if (isRangeMode) cancelRangeMode(); else setIsRangeMode(true); }} className={`flex items-center gap-2 px-3 py-1.5 rounded-lg text-sm transition-all border ${ isRangeMode ? 'bg-cyan-900/40 border-cyan-500 text-cyan-300 animate-pulse' : 'bg-slate-700 hover:bg-slate-600 border-transparent text-slate-300' }`}><MoveHorizontal className="w-4 h-4"/>{isRangeMode ? '선택 취소' : '범위 선택'}</button></div><div className="flex flex-wrap items-center gap-3"><div className="flex bg-slate-800 rounded-lg p-1 border border-slate-700"><button onClick={() => setViewColumns(1)} title="1열 보기" className={`px-2 py-1 rounded-md text-xs font-bold transition-colors ${viewColumns === 1 ? 'bg-slate-600 text-white' : 'text-slate-400 hover:text-white'}`}>1열</button><button onClick={() => setViewColumns(2)} title="2열 보기" className={`px-2 py-1 rounded-md text-xs font-bold transition-colors ${viewColumns === 2 ? 'bg-slate-600 text-white' : 'text-slate-400 hover:text-white'}`}>2열</button><button onClick={() => setViewColumns(3)} title="3열 보기" className={`px-2 py-1 rounded-md text-xs font-bold transition-colors ${viewColumns === 3 ? 'bg-slate-600 text-white' : 'text-slate-400 hover:text-white'}`}>3열</button></div><div className="w-px h-6 bg-slate-700"></div><button onClick={handleStartIncorrectQuiz} disabled={incorrectWords.length === 0} className="flex items-center gap-2 px-3 py-1.5 bg-red-900/30 border border-red-700/50 hover:bg-red-900/50 disabled:opacity-30 disabled:cursor-not-allowed rounded-lg text-sm text-red-200 transition-colors"><RotateCcw className="w-4 h-4"/>오답 복습</button><button onClick={handleStartFavoriteQuiz} className="flex items-center gap-2 px-3 py-1.5 bg-yellow-900/30 border border-yellow-700/50 hover:bg-yellow-900/50 rounded-lg text-sm text-yellow-200 transition-colors"><Star className="w-4 h-4 fill-yellow-500 text-yellow-500"/>즐겨찾기</button><button onClick={handleStartSelectedQuiz} disabled={selectedIds.size === 0} className="flex items-center gap-2 px-3 py-1.5 bg-purple-600 hover:bg-purple-500 disabled:bg-slate-800 disabled:text-slate-600 disabled:cursor-not-allowed rounded-lg text-sm text-white font-bold transition-colors shadow-lg shadow-purple-900/20"><Play className="w-4 h-4 fill-white"/>선택 학습</button></div></div>
        {isRangeMode && (<div className="bg-cyan-900/20 border border-cyan-500/50 rounded-xl p-3 flex items-center justify-center text-cyan-200 text-sm font-medium animate-slide-up"> {rangeStartId === null ? (<span>👇 시작할 단어를 선택하세요 (클릭)</span>) : (<span>👇 마지막 단어를 선택하세요 (여기까지 선택됨)</span>)} </div>)}
      </div>
      {filteredWords.length === 0 ? (<div className="text-center py-20 text-slate-500 bg-slate-900/50 rounded-2xl border border-slate-800"><p className="mb-2">{filterType === 'REVIEW' ? '틀린 단어가 없습니다! 🎉' : '등록된 단어가 없습니다.'}</p>{filterType === 'ALL' && <p className="text-sm">새로운 단어장을 업로드해보세요.</p>}</div>) : (
        <div className={`grid gap-3 transition-all ${ viewColumns === 1 ? 'grid-cols-1' : viewColumns === 2 ? 'grid-cols-1 md:grid-cols-2' : 'grid-cols-1 md:grid-cols-2 lg:grid-cols-3' }`}>
          {filteredWords.map(word => {
            const isRangeStart = rangeStartId === word.id;
            return (
                <div key={word.id} className={`relative rounded-xl p-4 border transition-all flex gap-4 cursor-pointer select-none h-full ${isRangeStart ? 'ring-2 ring-cyan-400 border-cyan-400 bg-cyan-900/20 z-10 scale-[1.02]' : ''} ${!isRangeStart && selectedIds.has(word.id) ? 'border-purple-500 bg-slate-800/80' : 'bg-slate-800 border-slate-700 hover:border-slate-500'}`}
                    onClick={(e) => { if ((e.target as HTMLElement).closest('button') || (e.target as HTMLElement).closest('input')) return; handleCardClick(word.id); }}>
                    <div className="flex flex-col items-center justify-center w-8 shrink-0">{isRangeStart ? (<div className="w-6 h-6 rounded bg-cyan-500 flex items-center justify-center text-slate-900 font-bold text-xs">시작</div>) : (<div className={`transition-colors ${selectedIds.has(word.id) ? 'text-purple-500' : 'text-slate-600 group-hover:text-slate-500'}`}> {selectedIds.has(word.id) ? <CheckSquare className="w-6 h-6"/> : <Square className="w-6 h-6"/>}</div>)}</div>
                    <div className="flex-1 min-w-0 flex flex-col h-full">
                        <div className="flex items-center justify-between mb-1"><div className="flex items-center gap-2 min-w-0"><h3 className="text-lg font-bold text-white truncate">{word.term}</h3><button onClick={(e) => { e.stopPropagation(); speak(word.id, word.term); }} className={`p-1 transition-colors shrink-0 ${playingId === word.id ? 'text-purple-400' : 'text-slate-500 hover:text-purple-400'}`} disabled={playingId !== null && playingId !== word.id}>{playingId === word.id ? <Loader2 className="w-4 h-4 animate-spin"/> : <Volume2 className="w-4 h-4" />}</button></div><button onClick={(e) => { e.stopPropagation(); onToggleFavorite(word.id); }} className="p-1 hover:scale-110 transition-transform shrink-0"><Star className={`w-5 h-5 ${word.isFavorite ? 'fill-yellow-400 text-yellow-400' : 'text-slate-600'}`} /></button></div>
                        <p className="text-indigo-200 text-base mb-2 line-clamp-2">{word.definition}</p>
                        <div className="mb-3 flex-1">{word.exampleSentence ? (<div className="bg-slate-900/50 p-3 rounded-lg border border-slate-700/50 text-sm cursor-text" onClick={e => e.stopPropagation()}><p className="text-slate-300 font-medium mb-1 line-clamp-3">"{word.exampleSentence}"</p><p className="text-slate-500 text-xs line-clamp-2">{word.exampleTranslation}</p></div>) : (<button onClick={(e) => { e.stopPropagation(); handleGenerateExample(word); }} className="text-xs flex items-center gap-1 text-purple-400 hover:text-purple-300 transition-colors bg-purple-900/20 px-2 py-1 rounded-md" disabled={generatingExampleId === word.id}>{generatingExampleId === word.id ? (<><Loader2 className="w-3 h-3 animate-spin"/> 생성중...</>) : (<><Sparkles className="w-3 h-3"/> AI 예문</>)}</button>)}</div>
                        <div className="flex items-center gap-3 text-xs text-slate-500 mt-auto pt-2 border-t border-slate-700/50">{word.incorrectCount > 0 && (<span className="px-2 py-0.5 bg-orange-900/50 text-orange-300 rounded-full border border-orange-800 shrink-0">오답 {word.incorrectCount}</span>)}<div className="flex items-center gap-1 ml-auto"><span>LV</span><div className="w-10 h-1 bg-slate-700 rounded-full overflow-hidden"><div className={`h-full ${word.masteryLevel >= 80 ? 'bg-green-500' : word.masteryLevel >= 40 ? 'bg-yellow-500' : 'bg-red-500'}`} style={{ width: `${word.masteryLevel}%` }}></div></div></div></div>
                        <div className="mt-2" onClick={e => e.stopPropagation()}>{editingId === word.id ? (<div className="flex gap-2"><input type="text" value={noteInput} onChange={(e) => setNoteInput(e.target.value)} placeholder="메모..." className="flex-1 bg-slate-900 border border-slate-600 rounded-lg px-2 py-1 text-xs text-white focus:border-purple-500 outline-none min-w-0" autoFocus/><button onClick={() => saveNote(word.id)} className="p-1 bg-purple-600 rounded-lg text-white hover:bg-purple-500 shrink-0"><Save className="w-3 h-3" /></button></div>) : (<div onClick={() => startEditing(word)} className="group flex items-center gap-2 text-xs text-slate-500 hover:text-slate-300 cursor-pointer"><Edit3 className="w-3 h-3 opacity-50 group-hover:opacity-100" />{word.userNote ? (<span className="text-purple-300 line-clamp-1">{word.userNote}</span>) : (<span className="opacity-50 group-hover:opacity-100">메모...</span>)}</div>)}</div>
                    </div>
                </div>
            );
          })}
        </div>
      )}
    </div>
  );
};

export default WordList;